version: "3.9"

services:
  geodaisy:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "3000:3000"
      - "4173:4173"
    restart: unless-stopped
